### ISSUE TITLE
无法通过VPN进行穿越扫描（使用的华为vpn）

### ISSUE THREAD

**Issue by 2522595153** [rtcatc/Packer-Fuzzer#11]
建议
![image](https://user-images.githubusercontent.com/56664312/99405998-5a93d300-2928-11eb-9158-4197a2033fe2.png)

**Comment by 1277226940** [comment]
表哥 这个库按不上怎么搞啊 
![图片](https://user-images.githubusercontent.com/41365381/99473254-2ef30600-2985-11eb-99f7-3375fadd28ae.png)

**Comment by rtcatc** [comment]
这个应该是端口问题造成了，报错
已经在先前的更新中进行了修复，感谢您的反馈，若并非此原因您只需要再次回复此issue即可
