### ISSUE TITLE
每次运行结束都报错，说什么空字符

### ISSUE THREAD

**Issue by Oldman19** [rtcatc/Packer-Fuzzer#13]
![image](https://user-images.githubusercontent.com/58176451/99613490-9cb93380-2a52-11eb-9ece-40f0f813979b.png)

**Comment by KpLi0rn** [comment]
方便加一下微信群吗 具体和您沟通一下

**Comment by KpLi0rn** [comment]
方便加一下微信群吗 具体和您沟通一下

**Comment by KpLi0rn** [comment]
可以尝试更新一下版本该问题昨天已经进行了修复

**Comment by rtcatc** [comment]
在稍早我们已经对此错误进行了更新，故我们先关闭此issue
若您的问题还未解决，您 只需要回复此issue即可
