### ISSUE TITLE
扫描误报css文件 为未授权

### ISSUE THREAD

**Issue by 2522595153** [rtcatc/Packer-Fuzzer#19]

**Comment by rtcatc** [comment]
您好有具体详情吗

**Comment by rtcatc** [comment]
已经在黑名单中添加css后缀：https://github.com/rtcatc/Packer-Fuzzer/commit/281819e7e70d42b14efe125a43974016638a052a
暂时将此issue关闭，若此问题未被成功修复您只需要再次回复即可
