### ISSUE TITLE
扫描误报，或者信息缺失

### ISSUE THREAD

**Issue by hyccgit** [rtcatc/Packer-Fuzzer#20]
![image](https://user-images.githubusercontent.com/24220639/99763005-b8950600-2b34-11eb-81d2-f86bee9f30d0.png)
这边这里检测出了文件上传，但是并没有显示api的信息，这个检测并没有错，确实有文件上传，但是api的具体信息有缺失

**Comment by hyccgit** [comment]
任意文件上传扫描出来了，但是html报告里面没有吧api的路径弄出来

**Comment by rtcatc** [comment]
感谢您的反馈，正在排查问题中

**Comment by rtcatc** [comment]
你好，已经定位到具体出错位置，正在修复

**Comment by rtcatc** [comment]
已在v1.0.8的更新中修复：https://github.com/rtcatc/Packer-Fuzzer/commit/04681112671bb9c986446fd47b79985430696b72
若未成功修复，您只需要再回复此issue即可，谢谢您及时的反馈
