### ISSUE TITLE
带端口的扫描无法成功

### ISSUE THREAD

**Issue by godamos** [rtcatc/Packer-Fuzzer#21]
比如：PackerFuzzer.py -u “http://www.baidu.com:81” 无法扫描

[16:38:18] 正在解析网页中...
[16:38:18] 网页解析完毕，共发现4个JS文件
[Err] unable to open database file
[16:38:18] 正在暴力检测JS文件中...
[16:38:18] JS文件收集结束，开始提取平台API...
[16:38:18] 提取API总数过少，自动开启暴力提取模式
[16:38:18] 提取流程结束，初步提取API可能结果数：0
[16:38:18] 正在检测目标响应状态中...
0it [00:00, ?it/s]
[16:38:18] 目标响应状态检测结束，开始漏洞检测...
[16:38:18] 开始检测未授权访问漏洞
[16:38:18] 开始检测敏感信息泄露漏洞
[16:38:18] 开始检测CORS漏洞
[Err] 'access-control-allow-origin'
[16:38:18] 检测报告正在生成中...
[16:38:51] 检测报告生成完毕！
[-] 全部扫描及检测完毕，Packer Fuzzer团队感谢您的使用！

**Comment by rtcatc** [comment]
使用的是最新版吗？

**Comment by godamos** [comment]
是的  我刚重新下的 也存在这个问题，而且
  File "E:\Packer-Fuzzer-master\lib\reports\CreatHtml.py", line 328 缩进好像也有问题

**Comment by rtcatc** [comment]
> 是的 我刚重新下的 也存在这个问题，而且
> File "E:\Packer-Fuzzer-master\lib\reports\CreatHtml.py", line 328 缩进好像也有问题

这个已经修复了

**Comment by rtcatc** [comment]
缩进问题已经修复，端口问题排查中

**Comment by rtcatc** [comment]
![image](https://user-images.githubusercontent.com/15169833/99785172-14539500-2b1d-11eb-968f-e15a0d25d73a.png)
我这里测试没问题的，可能win下面的兼容问题，方便加一下KpLi0rn的微信探讨一下吗？感谢

**Comment by rtcatc** [comment]
问题确实存在，已经定位到问题所在位置，感谢您的反馈！

**Comment by rtcatc** [comment]
![image](https://user-images.githubusercontent.com/15169833/99796581-08240380-2b2e-11eb-9042-ceaca3f86ab4.png)
已经在最近一次更新中修复了此错误：https://github.com/rtcatc/Packer-Fuzzer/commit/6bcac6c2a4fd00ee0d19dcc38f8bc72040399135 https://github.com/rtcatc/Packer-Fuzzer/commit/9d55d43bd2c52edd2ebdfe8606a279598d413719
感谢您的反馈，若此问题为被成功修复，您只需要回复此ISSUE即可

**Comment by rtcatc** [comment]
![image](https://user-images.githubusercontent.com/15169833/99796968-ab751880-2b2e-11eb-8886-8eef6f9c8ef8.png)
已经在最近一次更新中修复了此错误：https://github.com/rtcatc/Packer-Fuzzer/commit/6bcac6c2a4fd00ee0d19dcc38f8bc72040399135 https://github.com/rtcatc/Packer-Fuzzer/commit/9d55d43bd2c52edd2ebdfe8606a279598d413719
感谢您的反馈，若此问题为被成功修复，您只需要回复此ISSUE即可
