### ISSUE TITLE
能否保存提取的API结果

### ISSUE THREAD

**Issue by superboy-zjc** [rtcatc/Packer-Fuzzer#30]
在测试时发现，在提取API后，Packet-Fuzzer会进行API有效测试，当无效时会认为这是一个无效的API不去存储。但我在测试时，却发现其实很多API是存在越权的，需要手工去测试。所以能否增加一个逻辑，当API无效时，也保存API提取结果，供人工参考测试。

**Comment by rtcatc** [comment]
您好，packer-fuzzer会对每一次检测都在tmp目录下的项目文件内生成一个随机tag的.db文件，里面缓存了全部的数据

感谢您的建议，后期我们会优化交互！
