### ISSUE TITLE
一些试用的小问题

### ISSUE THREAD

**Issue by minofmax** [rtcatc/Packer-Fuzzer#32]
首先感谢开源这么优秀的扫描工具。对于安全从业人员来讲，看大佬们写的工具，确实是牛。

这次在试用的时候发现了一丢丢小问题。
1.js解析的时候api获取不全，有点少。针对我们的一个网站扫了下，拿到了11个api接口，全是get接口和重复的，实际总共的接口数量大概在60个上下。
2.在漏洞检测逻辑上可能有点小问题，譬如，扫描报告中的未授权，但是我们这个网站有些接口是开放的，所以有些接口不需要鉴权，并且有些需要登录的接口，我们在接口状态码返回的是类似于20000这类自定义错误码，是属于访问失败。这块可能检测逻辑稍微有点小问题。

**Comment by rtcatc** [comment]
您好，感谢您的反馈与支持！关于接口重复的问题我们会在近期修复

针对第二点的误报，您可以在/config.ini文件内增加属于自己企业产品的规则哦，例如：

`[vulnTest]
resultFilter = 20000`

**Comment by minofmax** [comment]
> 您好，感谢您的反馈与支持！关于接口重复的问题我们会在近期修复
> 
> 针对第二点的误报，您可以在/config.ini文件内增加属于自己企业产品的规则哦，例如：
> 
> `[vulnTest] resultFilter = 20000`

收到，后面我再试试
