### ISSUE TITLE
Could not find a version that satisfies the requirement execjs (from versions: none)

### ISSUE THREAD

**Issue by xxsmile123** [rtcatc/Packer-Fuzzer#34]
![image](https://user-images.githubusercontent.com/43473886/117414832-2f3e8800-af4a-11eb-9ec6-924feff12840.png)
无法下载到对应版本的execjs包

**Comment by rtcatc** [comment]
错误已经修复，感谢提醒：0ff859ef3a5fd239457512eedf215cda05b669e4
谢谢！
