### ISSUE TITLE
异步JS文件提取失败

### ISSUE THREAD

**Issue by KinofRikin** [rtcatc/Packer-Fuzzer#35]
报错：[Err] unable to open database file
报错截图：
![image](https://user-images.githubusercontent.com/18413058/121642712-7ed12000-cac3-11eb-9d3a-001b860422c9.png)

**Comment by rtcatc** [comment]
能私聊我log吗 或者url地址：admin@rtcatc.com
我朋友微信号: KpLi0rnSec

**Comment by rtcatc** [comment]
Bug已经修复，感谢支持：https://github.com/rtcatc/Packer-Fuzzer/commit/e5ac19cee4e5ce9f4ad8c4f8e6b3ae15e23253f4
