### ISSUE TITLE
2个小bug和1个建议

### ISSUE THREAD

**Issue by theLSA** [rtcatc/Packer-Fuzzer#38]
release v1.3
bug:
1.js文件的url开头为//时会直接拼接在扫描目标域名后导致bug。
![packer-fuzzer-issue-2021-07-01_10-17](https://user-images.githubusercontent.com/28248956/124113959-9ab25b00-da9e-11eb-8209-41350f3157ae.png)
![packer-fuzzer-issue-2021-07-01_10-22](https://user-images.githubusercontent.com/28248956/124113969-9dad4b80-da9e-11eb-9583-24643f3a23d6.png)
![packer-fuzzer-issue-2021-07-01_18-45](https://user-images.githubusercontent.com/28248956/124113975-a140d280-da9e-11eb-829a-bd5ab8ce397a.png)

2.生成的html报告v1.3版本的还显示1.2。
![packer-fuzzer-issue-2021-07-01_10-26](https://user-images.githubusercontent.com/28248956/124114010-aaca3a80-da9e-11eb-9ab7-26e02612dda4.png)

建议：
增加直接扫描指定js文件的功能，不用-u，建议可以在-j参数上处理（或者增加参数如--j-without-url）。
在处理bug-1的问题时-j扫描指定的js文件会出现重复已存在的问题
python3 PackerFuzzer.py -u "http://f.xxx.com/htmlpages/page#/login" -f 1 -j "https://g.xxx.com/web/feet-model-admin/1.5.5/static/js/app.js"

Downloading：mini-login-embedder-min.js
[10:23:03] Downloading：vendor.js
[10:23:04] Downloading：app.js
[10:23:05] Downloading：manifest.js
[10:23:05] The corresponding file already exists：app.js

**Comment by rtcatc** [comment]
谢谢您宝贵的意见，我们已经开始着手定位异常点

**Comment by rtcatc** [comment]
可否方便邮件我测试地址： pocsir@qq.com / admin@hackinn.com
或者添加您微信：我朋友微信号: KpLi0rnSec

**Comment by theLSA** [comment]
已发送至pocsir@qq.com

**Comment by rtcatc** [comment]
已经修复，感谢支持！
Commit: https://github.com/rtcatc/Packer-Fuzzer/commit/3b86f52382ff0eff502a92a3d97a8431b0f2a628
