### ISSUE TITLE
安装依赖后爆错 windows平台 

### ISSUE THREAD

**Issue by SummerSec** [rtcatc/Packer-Fuzzer#4]
E:\信息收集\Packer-Fuzzer>py -3 PackerFuzzer.py
Traceback (most recent call last):
  File "PackerFuzzer.py", line 4, in <module>
    from lib.Controller import Project
ModuleNotFoundError: No module named 'lib.Controller'

**Comment by rtcatc** [comment]
不应该的呀，lib.Controller就是lib文件夹下面的Controller.py文件

**Comment by rtcatc** [comment]
这里给出两点看看能不能解决：
1. 清除所有的python缓存，所有的.pyc文件，所有的__pycache__目录；
2. 使用python3 PackerFuzzer.py -u xxx 命令代替py -3 命令

**Comment by SummerSec** [comment]
> 不应该的呀，lib.Controller就是lib文件夹下面的Controller.py文件
我也好奇，从GitHub下载了两次，都是一样的错误
![image](https://user-images.githubusercontent.com/47944478/99236190-d65f2400-2831-11eb-976d-c49791ac4c3e.png)

**Comment by rtcatc** [comment]
我等下开一个新的win虚拟机测试一下

**Comment by SummerSec** [comment]
解决了，楼主应该是把__init__.py文件删除了，在对应文件下新键这个文件就好了。

**Comment by SummerSec** [comment]
![image](https://user-images.githubusercontent.com/47944478/99237395-5c2f9f00-2833-11eb-9870-0c14c2661bf1.png)

**Comment by rtcatc** [comment]
感谢反馈！
后续为兼容此文件将会默认添加

**Comment by rtcatc** [comment]
已在v1.0.1中修复此问题：https://github.com/rtcatc/Packer-Fuzzer/commit/d4633390d7df6dc1c622215dc73f2bbdf9fd1316
感谢 您对此开源项目做出的贡献
