### ISSUE TITLE
结果保存出错

### ISSUE THREAD

**Issue by Bluestar-coder** [rtcatc/Packer-Fuzzer#48]
[!] 共发现1个安全漏洞: 高危1个, 中危0个, 低危0个
[17:31:15] 检测报告正在生成中...
[Err] local variable 'js_path' referenced before assignment
[Err] local variable 'vuln_detail' referenced before assignment
[17:31:18] 检测报告生成完毕！
[-] 全部扫描及检测完毕，Packer Fuzzer团队感谢您的使用！

report目录并没有该目标报告

**Comment by rtcatc** [comment]
问题定位完毕，后期会修复
