### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by wubantudl** [rtcatc/Packer-Fuzzer#49]
Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)')

哥哥，能抽空解答一下这个错误吗

**Comment by rtcatc** [comment]
-f（--flag）

SSL连接安全选项，当为空时默认关闭状态，在此状态下将会阻止一切不安全的连接。若您希望忽略SSL安全状态，您可使用1命令开启，将会忽略一切证书错误，例如：-f 1；
