### ISSUE TITLE
html 提取chunk 类js出错

### ISSUE THREAD

**Issue by chen1sheng** [rtcatc/Packer-Fuzzer#51]
如下图，当html中出现chunk类js时，脚本能识别到，但是拼接路径时直接跟路径访问了，因为没有加 /static/js/ ，结果全部报404

![image](https://user-images.githubusercontent.com/44370914/147410438-7c00e901-68f9-4fca-8d53-04de5cd3fb33.png)

**Comment by rtcatc** [comment]
![image](https://user-images.githubusercontent.com/15169833/147941825-6c21b415-52ef-4af7-95fa-eac21b957762.png)
您好，首先非常感谢您支持我们的工具！
在您发表的图片内，我没有看见类似于我截图所示的“xxx = /static/js/”语句，这样会导致工具在运行时无法追加正确的路径，请问可否私发我完整的js内容，以便我们后续定位漏洞（admin@hackinn.com）,感谢！
祝新年快乐！

**Comment by rtcatc** [comment]
ISSUE先关闭，您可以随时重新开启
