### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by linuxdy** [rtcatc/Packer-Fuzzer#63]
requests.exceptions.SSLError: HTTPSConnectionPool(host='xxxxxx, port=xxxxx): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))

**Comment by rtcatc** [comment]
Dear [linuxdy](https://github.com/linuxdy)
 Try to use `-f 1` command to ignore SSL error
 Thanks for using
