### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by windmoon-Lotus** [rtcatc/Packer-Fuzzer#64]
可以指定本地目录然后递归分析嘛？如果可以配上获取网站所有资源的插件食用起来就更方便了
https://github.com/up209d/ResourcesSaverExt 

如果域名或者baseurl不对或者对也能把提取出的api在单独存放一份嘛，不同域名碰撞也会很方便的

**Comment by rtcatc** [comment]
使用最新版本的Packer Fuzzer，会有缓存文件位置提示。该文件为sqlite3格式，其中包含所有的原始数据，包括您所说的api列表：
<img width="818" alt="image" src="https://user-images.githubusercontent.com/15169833/212855702-d92946c1-ed36-42e2-8953-65fc467e3f55.png">
至于指定本地目录文件递归分析，目前还无法实现，可以通过启动本地服务器及使用`--ah`命令来实现。

感谢您的支持与建议！
