### ISSUE TITLE
html报告展示

### ISSUE THREAD

**Issue by Ludovicofu** [rtcatc/Packer-Fuzzer#66]
![image](https://user-images.githubusercontent.com/91811209/212528950-bc263e3e-5c1d-4068-b68d-44386f1a25b6.png)
没渲染出来，html代码无改变，谷歌、火狐浏览器均为这样

**Comment by rtcatc** [comment]
您可以尝试将`/doc/template/html/res`文件夹复制至报告目录所在的文件下，然后重新刷新报告。若问题还未解决，可随时回复
