### ISSUE TITLE
windows python3.9安装依赖报错：

### ISSUE THREAD

**Issue by wingring** [rtcatc/Packer-Fuzzer#71]
windows python3.9安装依赖报错：
Collecting docx2pdf
  Using cached docx2pdf-0.1.8-py3-none-any.whl (6.7 kB)
Collecting docx2txt
  Using cached docx2txt-0.8.tar.gz (2.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call  #last):

**Comment by rtcatc** [comment]
非Packer Fuzzer工具问题 我先关闭
建议使用pip安装
