### ISSUE TITLE
可以新增一个专门导出api清单的选项吗

### ISSUE THREAD

**Issue by Trisscute** [rtcatc/Packer-Fuzzer#77]
因为测试api很多时候都是为了提取然后手工测试，可以设置一个选项专门只导出api提升效率，例如导出一个excel表格一行api一行来自哪个源文件

**Comment by BigYoungs** [comment]
自己开发了导出api功能，导出api清单到.json文件，感兴趣可以看看：https://sec.bigyoung.cn/article/Packer-Fuzzer-Plus/ 

> 因为测试api很多时候都是为了提取然后手工测试，可以设置一个选项专门只导出api提升效率，例如导出一个excel表格一行api一行来自哪个源文件

**Comment by rtcatc** [comment]
在PackerFuzzer项目文件夹内你可以找到tmp文件夹，在里面有每个项目的缓存 其中有个.db的sqlite数据库，点开来里面有项目的全部信息 api等信息也包含在里面啦，我认为比单独输出excel更高效 里面的数据更多并且sql语句处理很方便 感谢您的支持和建议！ Je vous remerci !!
