### ISSUE TITLE
ImportError: cannot import name 'parse_xml' from 'docx.oxml'

### ISSUE THREAD

**Issue by qiuluo-oss** [rtcatc/Packer-Fuzzer#78]
ImportError: cannot import name 'parse_xml' from 'docx.oxml' (/usr/local/lib/python3.8/dist-packages/docx/oxml/__init__.py)
![image](https://github.com/rtcatc/Packer-Fuzzer/assets/72497146/6f45e7e1-21f4-4813-adf6-b70673980a00)

**Comment by Arrowzzzzzz** [comment]
使用pip3 install python-docx==0.8.11  在1.0.0版本中存在兼容性问题，具体见链`https://github.com/python-openxml/python-docx/issues/1256`
<img width="711" alt="image" src="https://github.com/rtcatc/Packer-Fuzzer/assets/30648109/29b9e151-d52e-42e6-8aa8-0fa89a5c5365">

**Comment by XIAOQIUNI** [comment]
这个怎么解决

**Comment by rtcatc** [comment]
与https://github.com/rtcatc/Packer-Fuzzer/issues/84合并，关闭
