### ISSUE TITLE
ImportError: cannot import name 'parse_xml' from 'docx.oxml' (/usr/local/lib/python3.8/dist-packages/docx/oxml/__init__.py)

### ISSUE THREAD

**Issue by mengkidlufei** [rtcatc/Packer-Fuzzer#79]
ImportError: cannot import name 'parse_xml' from 'docx.oxml' (/usr/local/lib/python3.8/dist-packages/docx/oxml/__init__.py)

**Comment by Arrowzzzzzz** [comment]
使用pip3 install python-docx==0.8.11  在1.0.0版本中存在兼容性问题，具体见链`https://github.com/python-openxml/python-docx/issues/1256`
<img width="711" alt="image" src="https://github.com/rtcatc/Packer-Fuzzer/assets/30648109/29b9e151-d52e-42e6-8aa8-0fa89a5c5365">

**Comment by mengkidlufei** [comment]
还是好人多啊

**Comment by o7966** [comment]
太赞了

**Comment by JonathanSeed** [comment]
谢谢你 陌生人

**Comment by abc1985117** [comment]
niub

**Comment by Leesj0930** [comment]
搞了半天，还得是好心人

**Comment by CHOSEN1-Z13** [comment]
还是好人多啊 牛*

**Comment by rtcatc** [comment]
与https://github.com/rtcatc/Packer-Fuzzer/issues/84合并，关闭
