### ISSUE TITLE
/usr/local/lib/python3.9/dist-packages/node_vm2/__init__.py:17: FutureWarning: node_vm2 is deprecated. Please use deno_vm instead.   warnings.warn("node_vm2 is deprecated. Please use deno_vm instead.", FutureWarning)

### ISSUE THREAD

**Issue by NHPT** [rtcatc/Packer-Fuzzer#81]
![image](https://github.com/rtcatc/Packer-Fuzzer/assets/42366434/f8442530-a6fd-44dd-84c0-1d7d34dbe86c)

**Comment by d0ctorsec** [comment]
我也遇到这个问题了
/opt/homebrew/lib/python3.11/site-packages/node_vm2/__init__.py:17: FutureWarning: node_vm2 is deprecated. Please use deno_vm instead.

**Comment by Mrwithnomoney** [comment]
我也遇到这个问题了，不知道怎么解决
![image](https://github.com/rtcatc/Packer-Fuzzer/assets/97926637/c5562186-5ea4-4702-8479-ea844a43fae4)

**Comment by NoneVector** [comment]
忽略这个，没有问题可以使用
![Snipaste_2024-02-16_11-21-11](https://github.com/rtcatc/Packer-Fuzzer/assets/114130226/821a1f74-0c8f-44c1-8962-e91ed461ce22)

**Comment by HalleyC** [comment]
可以试试：
pip uninstall python-docx先卸载安装的高版本
再输入pip install python-docx==0.8.11 安装指定版本即可
参考来源：https://blog.csdn.net/wushangyu32335/article/details/135574085

**Comment by rtcatc** [comment]
与https://github.com/rtcatc/Packer-Fuzzer/issues/84合并，关闭
