### ISSUE TITLE
KeyError: 'zh'

### ISSUE THREAD

**Issue by ZXX-9527** [rtcatc/Packer-Fuzzer#83]
![图片](https://github.com/rtcatc/Packer-Fuzzer/assets/52208894/af253e3d-7229-40a1-b86e-b730f388dbf0)
你好，运行时发生一个KeyError，尝试过zh和en都会报错

**Comment by rtcatc** [comment]
方便提供下log文件信息以便于我们快速定位吗？可先尝试使用-l zh命令直接指定中文语言 Envoyé de mon iPhoneLe 5 janv. 2024 à 17:05, 周星星 ***@***.***> a écrit :﻿
default.png (view on web)
你好，运行时发生一个KeyError，尝试过zh和en都会报错

**Comment by ZXX-9527** [comment]
> 方便提供下log文件信息以便于我们快速定位吗？可先尝试使用-l zh命令直接指定中文语言 Envoyé de mon iPhoneLe 5 janv. 2024 à 17:05, 周星星 ***@***.***> a écrit :﻿ default.png (view on web) 你好，运行时发生一个KeyError，尝试过zh和en都会报错 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-l zh 和 -l en都试过，都会报相同错误，logs文件夹下面也没有生成任何日志文件
![图片](https://github.com/rtcatc/Packer-Fuzzer/assets/52208894/ad07e06a-9f37-4053-9372-235580d5b7a3)

**Comment by rtcatc** [comment]
直接切换到packer fuzzer目录下运行文件
