### ISSUE TITLE
python3.11新环境pip安装运行报错

### ISSUE THREAD

**Issue by rtcatc** [rtcatc/Packer-Fuzzer#84]
ImportError: cannot import name 'OxmlElement' from 'docx.oxml.xmlchemy' (/opt/anaconda3/lib/python3.11/site-packages/docx/oxml/xmlchemy.py)

**Comment by rtcatc** [comment]
报错原因 最新版本升级了API 
Ref: https://github.com/python-openxml/python-docx/issues/1256#issuecomment-1758075196

解决方法：
pip install python-docx==0.8.11

**Comment by rtcatc** [comment]
合并Issues:
https://github.com/rtcatc/Packer-Fuzzer/issues/81
https://github.com/rtcatc/Packer-Fuzzer/issues/78
https://github.com/rtcatc/Packer-Fuzzer/issues/79

问题早已修复 更新最新版即可

**Comment by yizhongbear** [comment]
现在来看，还是python-docx==0.8.11稳
![Uploading image.png…]()

**Comment by WUHUGAOHUANGSE** [comment]
妙
