### ISSUE TITLE
扫描报告中API清单没有信息

### ISSUE THREAD

**Issue by bayet** [rtcatc/Packer-Fuzzer#89]
在扫描结束后，无论是否存在漏洞，生成的报告中API清单里都没有信息，但是终端中有前五条API提取结果，和可能的API提取结果数

**Comment by rtcatc** [comment]
无图无真相 这让我咋看

**Comment by rtcatc** [comment]
长时间无回复 归档结束ISSUE 如有更新随时回复开启
