### ISSUE TITLE
[!] 检测到提取结果不准确，请输入新的BaseDir (使用逗号分隔)：

### ISSUE THREAD

**Issue by richard1230** [rtcatc/Packer-Fuzzer#91]
<img width="1396" alt="image" src="https://github.com/rtcatc/Packer-Fuzzer/assets/20439699/89bbfaf1-429a-45f1-b1d2-58bc985473d6">

遇到一个这种问题(检测到提取结果不准确，请输入新的BaseDir (使用逗号分隔)：)，应该怎么处理？

**Comment by richard1230** [comment]
也就是说怎么去寻找新的BaseDir，请教一下作者

**Comment by rtcatc** [comment]
我们推荐您通过自定义baseurl的方式来提高API拼接成功率，减少发包次数。找寻baseurl并不难，您只需要在对应目标站点中触发任何一个API并稍加观察缺失部分即可快速寻找到；

你去看network请求包 比如有个http://xx.com/api/v1/login/check的API 然后你去js搜索你发现只存在/login/check字符串那么/api/v1部分就是baseurl
