### ISSUE TITLE
 外网连接失败，请检查当前网络状况或者代理情况怎么解决

### ISSUE THREAD

**Issue by shiqing25** [rtcatc/Packer-Fuzzer#93]
![3aa9849fcdea34c215a4eefd900cf82](https://github.com/user-attachments/assets/903afa3c-7062-436f-ad0b-f0b85cd54202)

 外网连接失败，请检查当前网络状况或者代理情况

**Comment by rtcatc** [comment]
不影响工具使用，网络问题导致外联检测IP被禁了
